[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[theme]
primaryColor = "#FF7900"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#444444"
font = "sans serif"
